[project]
name = "pyaqsapi"
requires-python = ">=3.8"
dynamic = ["version", "dependencies", "optional-dependencies"]
description="Retrieve ambient air monitoring data from the United States Environmental Protection Agency’s (US EPA) Air Quality System (AQS) Data Mart API v2 interface."
authors = [
  {name = "Clinton Mccrowey", email = "mccrowey.clinton@epa.gov"},
]
maintainers = [
  {name = "Clinton Mccrowey", email = "mccrowey.clinton@epa.gov"}
]
readme = {file = "README.rst", content-type = "text/x-rst"}
license = {file = "LICENSE.rst"}
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]

[project.urls]
"Homepage" = "https://github.com/USEPA/pyaqsapi"
"AQS" = "https://www.epa.gov/aqs"
"AQS DataMart" = "https://aqs.epa.gov/aqsweb/documents/data_mart_welcome.html"
"AQS Data Mart API" = "https://aqs.epa.gov/aqsweb/documents/data_api.html"
"pyaqsapi API Documentation" = "https://usepa.github.io/pyaqsapi/"
"SOURCE" = "https://github.com/USEPA/pyaqsapi.git"
"RAQSAPI" = "https://github.com/USEPA/RAQSAPI"
"Issue Tracker" = "https://github.com/USEPA/pyaqsapi/issues"

[build-system]
requires = [
    "sphinx",
    "sphinxcontrib-napoleon",
	"setuptools>=42",
	"wheel"
]

build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
pythonpath = ["pyaqsapi"]
max-line-length = 85
combine-as-imports = true
show-source = true


[tool.ruff]
lint.select = ["I001",
               "I002",
               "E101",
               "D100",
               "D401",
               "D402",
               "D403",
               "D404",
               "D406",
               "D407",
               "D408",
               "D409",
               "D414",
               "D415",
               "D417",
               "D419"]
          
lint.extend-select = ["UP"]


exclude = [
    "__init__.py",
    ".git",
    ".tox",
    "ruff_cache",
    ".spyproject",
    ".github",
    ".vscode",
    "conf.py",
    "setup.py",
    "*tests/*"
]

[tool.ruff.lint.pydocstyle]
convention = "google"