name: new_build_and_test_pyaqsapi
run-name: A push event from ${{ github.actor }} caused a rebuilding and retesting of the pyaqsapi package via GitHub actions

on:
  push:
    branches:
      - main
      - github_workflow
  pull_request:
    branches:
      - main
      - github_workflow

defaults:
  run:
    shell: bash -el {0}
    
jobs:
  setup_environment:
    runs-on: ubuntu-latest
    env:
      AQSkey: ${{ secrets.AQSKEY }}
      AQSuser: ${{ secrets.AQSUSER }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          init-shell: >-
            bash
          cache-environment: true
          environment-name: pyaqsapi
          post-cleanup: 'all'
          shell: bash

      - name: Display Python and sphinx version and system info
        run: |
          conda init
          python -c "import platform; print(platform.uname())"
          sphinx-build --version

      - name: build and install pyaqsapi in a test environment using python-build and pip 
        run: |
          python -m build .
          pip install .

      - name: build apidocs
        run: |
          cd docs
          make clean
          sphinx-apidoc --ext-autodoc -o . ../pyaqsapi/
          make html
      
      - name: test_package
        env:
          AQSkey: ${{ secrets.AQSKEY }}
          AQSuser: ${{ secrets.AQSUSER }}
        run: pytest